robot:
  hardware_interface:
     loop_hz: 50 # hz
     joints:
       - left_wheel
       - right_wheel
  wheel_radius: 0.0825
  distance_betwen_wheels: 0.45
  direction_correction: 1
  serial_port: '/dev/ttyUSB0'
